// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbEj3R0-wrbQLpm0m1JJlEqqnn2H3lNCE',
    appId: '1:45173343678:web:7e9582d6db6a2cfa4665ef',
    messagingSenderId: '45173343678',
    projectId: 'petiverse-7d9f4',
    authDomain: 'petiverse-7d9f4.firebaseapp.com',
    storageBucket: 'petiverse-7d9f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPNym1KL9xqZ2iQimy8DJGNyynh20M7uM',
    appId: '1:45173343678:android:ab48f99caa3dcca54665ef',
    messagingSenderId: '45173343678',
    projectId: 'petiverse-7d9f4',
    storageBucket: 'petiverse-7d9f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdoReRi4VkLmvu6M6msb0MKQtjT7Sqg7E',
    appId: '1:45173343678:ios:8308878e80fa27974665ef',
    messagingSenderId: '45173343678',
    projectId: 'petiverse-7d9f4',
    storageBucket: 'petiverse-7d9f4.appspot.com',
    iosClientId: '45173343678-45qfmq92gptqngpu9r7uumlodbajjj2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.petiverse',
  );
}
